language: python
python:
  - "2.7"

virtualenv:
    system_site_packages: true

# whitelist
branches:
  only:
    - dev
    - master

before_install:
    - echo "before_install"
    - echo $VIRTUAL_ENV
    - df -h
    - date
    - pwd
    - uname -a
    - python -V

    # Xvfb stuff for clipboard functionality; see the travis-ci documentation
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy libatlas-dev liblapack-dev gfortran
    - sudo apt-get install -qq libfreeimage3
    - sudo apt-get install -qq libpng12-dev libtiff4-dev libwebp-dev
    - sudo apt-get install -qq python-scipy python-imaging python-matplotlib
    - pip install tabulate

script:
    - python setup.py install
    - python examples/random_feature_vectors.py
    - rm -f *.pkl
    - python examples/number_of_feature_vectors_performance-euclidean_distance.py
    - python examples/number_of_features_performance-euclidean_distance.py
    - rm -f *.pkl
    - rm -f *.png
    - python examples/iris.py
    - python examples/wine.py
    - python examples/metrics.py
    - python examples/alphas.py

# command to run tests
# script: nosetests
